"""identity access geo audit

Revision ID: 625d0f9db974
Revises: 
Create Date: 2026-08-26 14:46:28.518078

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (app.db.types.UTCDateTime).
import app.db.types  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = '625d0f9db974'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_te', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('slug', name='uq_districts_slug'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_districts_state_slug', 'districts', ['state', 'slug'], unique=False)
    op.create_table('permissions',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('label_en', sa.String(length=160), nullable=False),
    sa.Column('label_te', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_scoped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('key', name='uq_permissions_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label_te', sa.String(length=80), nullable=False),
    sa.Column('label_en', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('default_scope_type', sa.Enum('GLOBAL', 'DISTRICT', 'MANDAL', 'DESK', 'EDITION', 'SELF', name='scopetype', native_enum=False, length=20), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('key', name='uq_roles_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_roles_level', 'roles', ['level'], unique=False)
    op.create_table('users',
    sa.Column('name_te', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', 'DISABLED', name='userstatus', native_enum=False, length=20), server_default='active', nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('avatar_media_id', sa.BigInteger(), nullable=True),
    sa.Column('bio_te', sa.Text(), nullable=True),
    sa.Column('designation_te', sa.String(length=120), nullable=True),
    sa.Column('author_slug', sa.String(length=120), nullable=True),
    sa.Column('is_author', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('password_changed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('locked_until', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('author_slug', name=op.f('uq_users_author_slug')),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('phone', name='uq_users_phone'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'SESSION_REVOKED', 'OTP_REQUESTED', 'PASSWORD_CHANGED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'SUBMIT', 'REVIEW_START', 'APPROVE', 'REJECT', 'REQUEST_CHANGES', 'PUBLISH', 'UNPUBLISH', 'SCHEDULE', 'VERSION_RESTORE', 'ROLE_ASSIGNED', 'ROLE_REVOKED', 'PERMISSION_CHANGED', 'AI_RUN', 'AI_FLAG_CLEARED', 'MEDIA_UPLOAD', 'MEDIA_DELETE', 'EPAPER_UPLOAD', 'EPAPER_PUBLISH', 'HOTSPOT_SAVED', 'PUSH_CREATED', 'PUSH_APPROVED', 'PUSH_SENT', 'SETTING_CHANGED', name='auditaction', native_enum=False, length=30), nullable=False),
    sa.Column('before', mysql.JSON(), nullable=True),
    sa.Column('after', mysql.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_audit_log_action_created_at', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_log_actor_id_created_at', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_entity_type_entity_id_created_at', 'audit_log', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('mandals',
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_te', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_mandals_district_id_districts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandals')),
    sa.UniqueConstraint('district_id', 'slug', name='uq_mandals_district_id_slug'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_mandals_district_id'), 'mandals', ['district_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('sessions',
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('device_label', sa.String(length=160), nullable=True),
    sa.Column('platform', sa.Enum('WEB', 'ANDROID', 'IOS', 'CMS', 'UNKNOWN', name='sessionplatform', native_enum=False, length=20), nullable=False),
    sa.Column('refresh_hash', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=80), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('session_key', name='uq_sessions_session_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id_revoked_at', 'sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.Enum('GLOBAL', 'DISTRICT', 'MANDAL', 'DESK', 'EDITION', 'SELF', name='scopetype', native_enum=False, length=20), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_roles_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_user_roles_assignment'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_roles_scope', 'user_roles', ['scope_type', 'scope_id'], unique=False)
    op.create_index('ix_user_roles_user_id_role_id', 'user_roles', ['user_id', 'role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_user_id_role_id', table_name='user_roles')
    op.drop_index('ix_user_roles_scope', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_sessions_user_id_revoked_at', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_mandals_district_id'), table_name='mandals')
    op.drop_table('mandals')
    op.drop_index('ix_audit_log_entity_type_entity_id_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_id_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_action_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_roles_level', table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('ix_districts_state_slug', table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
