"""content taxonomy articles media

Revision ID: 1f20bffe3e95
Revises: 625d0f9db974
Create Date: 2026-08-26 15:25:21.855656

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations (app.db.types.UTCDateTime).
import app.db.types  # noqa: F401
from sqlalchemy.dialects import mysql

revision: str = '1f20bffe3e95'
down_revision: Union[str, None] = '625d0f9db974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_te', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('description_te', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_in_nav', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name='uq_categories_slug'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_categories_parent_id_sort', 'categories', ['parent_id', 'sort'], unique=False)
    op.create_table('tags',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_te', sa.String(length=140), nullable=False),
    sa.Column('name_en', sa.String(length=140), nullable=False),
    sa.Column('type', sa.Enum('PERSON', 'PLACE', 'ORG', 'TOPIC', 'EVENT', name='tagtype', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('slug', name='uq_tags_slug'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tags_type', 'tags', ['type'], unique=False)
    op.create_table('term_glossary',
    sa.Column('term_en', sa.String(length=160), nullable=False),
    sa.Column('term_te', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('PERSON', 'PLACE', 'ORG', 'TOPIC', 'EVENT', name='tagtype', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_glossary')),
    sa.UniqueConstraint('term_en', name='uq_term_glossary_term_en'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('media',
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'PDF', 'DOC', name='mediatype', native_enum=False, length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_provider', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('cdn_url', sa.String(length=700), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('blurhash', sa.String(length=60), nullable=True),
    sa.Column('caption_te', sa.Text(), nullable=True),
    sa.Column('alt_te', sa.String(length=500), nullable=True),
    sa.Column('credit', sa.String(length=200), nullable=True),
    sa.Column('copyright', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=20), server_default='own', nullable=False),
    sa.Column('ai_generated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=80), nullable=True),
    sa.Column('variants', mysql.JSON(), nullable=True),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index('ix_media_storage_provider_storage_key', 'media', ['storage_provider', 'storage_key'], unique=False)
    op.create_index('ix_media_type_created_at', 'media', ['type', 'created_at'], unique=False)
    op.create_index('ix_media_uploaded_by', 'media', ['uploaded_by'], unique=False)
    op.create_table('articles',
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title_te', sa.String(length=400), nullable=False),
    sa.Column('title_en', sa.String(length=400), nullable=True),
    sa.Column('sub_title_te', sa.String(length=500), nullable=True),
    sa.Column('summary_te', sa.String(length=1000), nullable=True),
    sa.Column('body', mysql.JSON(), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('mandal_id', sa.BigInteger(), nullable=True),
    sa.Column('hero_media_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'SCHEDULED', 'PUBLISHED', 'UNPUBLISHED', 'REJECTED', 'ARCHIVED', name='articlestatus', native_enum=False, length=20), server_default='draft', nullable=False),
    sa.Column('workflow_state', sa.Enum('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'UPDATE_REVIEW', 'UNPUBLISHED', 'REJECTED', name='workflowstate', native_enum=False, length=20), server_default='DRAFT', nullable=False),
    sa.Column('is_breaking', sa.Boolean(), nullable=False),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('byline_te', sa.String(length=200), nullable=True),
    sa.Column('source_credit', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=20), server_default='own', nullable=False),
    sa.Column('ai_generated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ai_job_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_model', sa.String(length=80), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=400), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('reading_time_sec', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('scheduled_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('first_published_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('corrected_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('correction_note_te', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('published_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_articles_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_articles_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_articles_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_articles_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_articles_district_id_districts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hero_media_id'], ['media.id'], name=op.f('fk_articles_hero_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], name=op.f('fk_articles_mandal_id_mandals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_articles_published_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_articles_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('short_id', name='uq_articles_short_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_articles_author_id_published_at', 'articles', ['author_id', 'published_at'], unique=False)
    op.create_index('ix_articles_category_id_published_at', 'articles', ['category_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_deleted_at'), 'articles', ['deleted_at'], unique=False)
    op.create_index('ix_articles_district_id_published_at', 'articles', ['district_id', 'published_at'], unique=False)
    op.create_index('ix_articles_scheduled_at', 'articles', ['scheduled_at'], unique=False)
    op.create_index('ix_articles_slug', 'articles', ['slug'], unique=False)
    op.create_index('ix_articles_status_deleted_at_published_at', 'articles', ['status', 'deleted_at', 'published_at'], unique=False)
    op.create_index('ix_articles_status_published_at', 'articles', ['status', 'published_at'], unique=False)
    op.create_index('ix_articles_workflow_state_updated_at', 'articles', ['workflow_state', 'updated_at'], unique=False)
    op.create_table('article_media',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_media_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_article_media_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'media_id', 'role', name=op.f('pk_article_media')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('article_search_aliases',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_search_aliases_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_search_aliases')),
    sa.UniqueConstraint('article_id', 'alias', name='uq_article_search_aliases_article_id_alias'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_article_search_aliases_alias', 'article_search_aliases', ['alias'], unique=False)
    op.create_table('article_tags',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_tags_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_article_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_article_tags')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('article_versions',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', mysql.JSON(), nullable=False),
    sa.Column('changed_fields', mysql.JSON(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_versions_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_article_versions_changed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_versions')),
    sa.UniqueConstraint('article_id', 'version', name='uq_article_versions_article_id_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_article_versions_article_id_created_at', 'article_versions', ['article_id', 'created_at'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('from_state', sa.Enum('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'UPDATE_REVIEW', 'UNPUBLISHED', 'REJECTED', name='workflowstate', native_enum=False, length=20), nullable=True),
    sa.Column('to_state', sa.Enum('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'UPDATE_REVIEW', 'UNPUBLISHED', 'REJECTED', name='workflowstate', native_enum=False, length=20), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_workflow_transitions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_workflow_transitions_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transitions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_workflow_transitions_article_id_created_at', 'workflow_transitions', ['article_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_transitions_article_id_created_at', table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    op.drop_index('ix_article_versions_article_id_created_at', table_name='article_versions')
    op.drop_table('article_versions')
    op.drop_table('article_tags')
    op.drop_index('ix_article_search_aliases_alias', table_name='article_search_aliases')
    op.drop_table('article_search_aliases')
    op.drop_table('article_media')
    op.drop_index('ix_articles_workflow_state_updated_at', table_name='articles')
    op.drop_index('ix_articles_status_published_at', table_name='articles')
    op.drop_index('ix_articles_status_deleted_at_published_at', table_name='articles')
    op.drop_index('ix_articles_slug', table_name='articles')
    op.drop_index('ix_articles_scheduled_at', table_name='articles')
    op.drop_index('ix_articles_district_id_published_at', table_name='articles')
    op.drop_index(op.f('ix_articles_deleted_at'), table_name='articles')
    op.drop_index('ix_articles_category_id_published_at', table_name='articles')
    op.drop_index('ix_articles_author_id_published_at', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_media_uploaded_by', table_name='media')
    op.drop_index('ix_media_type_created_at', table_name='media')
    op.drop_index('ix_media_storage_provider_storage_key', table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_table('media')
    op.drop_table('term_glossary')
    op.drop_index('ix_tags_type', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_categories_parent_id_sort', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
