import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import * as cmsApi from '@/features/cms/api';
import { useAuth } from '@/stores/auth';
import { useI18n } from '@/i18n';

const ACTIONS:Record<string,Array<[string,string,string,string]>>={DRAFT:[['submit','సమర్పించండి','Submit','article.submit']],CHANGES_REQUESTED:[['submit','మళ్లీ సమర్పించండి','Resubmit','article.submit']],SUBMITTED:[['review','రివ్యూ ప్రారంభించండి','Start review','article.review'],['approve','ఆమోదించండి','Approve','article.approve'],['request-changes','మార్పులు కోరండి','Request changes','article.reject']],IN_REVIEW:[['approve','ఆమోదించండి','Approve','article.approve'],['request-changes','మార్పులు కోరండి','Request changes','article.reject'],['reject','తిరస్కరించండి','Reject','article.reject']],APPROVED:[['publish','ప్రచురించండి','Publish','article.publish']],PUBLISHED:[['unpublish','ప్రచురణ ఆపండి','Unpublish','article.unpublish']]};

export default function Articles(){const {language}=useI18n();const en=language==='en';const can=useAuth(s=>s.can);const qc=useQueryClient();const query=useQuery({queryKey:['cms','articles'],queryFn:()=>cmsApi.fetchArticles()});const transition=useMutation({mutationFn:({id,action}:{id:number;action:string})=>cmsApi.transitionArticle(id,action),onSuccess:()=>qc.invalidateQueries({queryKey:['cms','articles']})});return <main className="mx-auto max-w-6xl px-4 py-6"><header className="mb-5 flex items-center justify-between"><div><h1 className="th text-[24px] font-extrabold">{en?'Articles':'కథనాలు'}</h1><p className="text-[12px] text-muted">{en?'Editorial workflow from draft to publication':'డ్రాఫ్ట్ నుంచి ప్రచురణ వరకు సంపాదకీయ వర్క్‌ఫ్లో'}</p></div>{can('article.create')?<Link to="/admin/articles/new" className="rounded-control bg-brand px-4 py-2.5 font-bold text-white">{en?'New article':'కొత్త కథనం'}</Link>:null}</header>{query.isLoading?<p>{en?'Loading…':'లోడ్ అవుతోంది…'}</p>:null}{query.isError?<p className="text-breaking">{en?'Could not load articles.':'కథనాలు లోడ్ కాలేదు.'}</p>:null}<div className="overflow-x-auto rounded-card border border-rule bg-white"><table className="w-full min-w-[760px] text-left"><thead className="bg-paper font-sans text-[11px] uppercase text-muted"><tr><th className="p-3">{en?'Headline':'శీర్షిక'}</th><th>{en?'State':'స్థితి'}</th><th>{en?'Updated':'నవీకరణ'}</th><th>{en?'Actions':'చర్యలు'}</th></tr></thead><tbody>{query.data?.articles.map(a=><tr key={a.id} className="border-t border-rule-soft"><td className="p-3"><Link className="th font-bold hover:text-brand" to={`/admin/articles/${a.id}/edit`}>{en?(a.title_en||a.title_te):a.title_te}</Link><p className="font-mono text-[10px] text-muted">#{a.id} · {a.short_id}</p></td><td><span className="rounded-chip bg-info-tint px-2 py-1 text-[10px] font-bold text-info">{a.workflow_state.replaceAll('_',' ')}</span></td><td className="text-[11px] text-muted">{new Date(a.updated_at).toLocaleString(en?'en-IN':'te-IN')}</td><td><div className="flex flex-wrap gap-1">{(ACTIONS[a.workflow_state]??[]).filter(([, , ,p])=>can(p as Parameters<typeof can>[0])).map(([action,te,enLabel])=><button key={action} onClick={()=>transition.mutate({id:a.id,action})} className="rounded border border-rule px-2 py-1 text-[11px] font-semibold hover:text-brand">{en?enLabel:te}</button>)}</div></td></tr>)}</tbody></table>{!query.isLoading&&!query.data?.articles.length?<p className="p-6 text-center text-muted">{en?'No articles yet.':'ఇంకా కథనాలు లేవు.'}</p>:null}</div></main>}
