import { useMutation, useQueries, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import * as cmsApi from '@/features/cms/api';
import type { CmsArticle } from '@/types/cms';
import { useI18n } from '@/i18n';

const columns=[{state:'SUBMITTED',te:'సమర్పించినవి',en:'Submitted',action:'review',actionTe:'రివ్యూ ప్రారంభించండి',actionEn:'Start review'},{state:'IN_REVIEW',te:'రివ్యూలో',en:'In review',action:'approve',actionTe:'ఆమోదించండి',actionEn:'Approve'},{state:'APPROVED',te:'ఆమోదించినవి',en:'Approved',action:'publish',actionTe:'ప్రచురించండి',actionEn:'Publish'}];
function ageLabel(article:CmsArticle,en:boolean){const minutes=Math.max(0,Math.floor((Date.now()-new Date(article.updated_at).getTime())/60000));return minutes<60?`${minutes} ${en?'min':'ని.'}`:`${Math.floor(minutes/60)} ${en?'hr':'గం.'}`}
export default function ReviewQueue(){const {language}=useI18n();const en=language==='en';const client=useQueryClient();const queries=useQueries({queries:columns.map(c=>({queryKey:['cms','review',c.state],queryFn:()=>cmsApi.fetchArticles({state:c.state,limit:100})}))});const transition=useMutation({mutationFn:({id,action}:{id:number;action:string})=>cmsApi.transitionArticle(id,action),onSuccess:()=>client.invalidateQueries({queryKey:['cms']})});return <main className="mx-auto max-w-[1400px] px-4 py-6"><header className="mb-5"><h1 className="th text-[25px] font-extrabold">{en?'Editor review queue':'ఎడిటర్ రివ్యూ క్యూ'}</h1><p className="mt-1 text-[12px] text-muted">{en?'Live editorial status from submission to publication':'సమర్పణ నుంచి ప్రచురణ వరకు ప్రత్యక్ష సంపాదకీయ స్థితి'}</p></header><div className="grid gap-4 lg:grid-cols-3">{columns.map((c,i)=><section key={c.state} className="rounded-card border border-rule bg-paper p-3"><h2 className="mb-3 flex items-center justify-between font-bold"><span>{en?c.en:c.te}</span><span className="rounded-chip bg-white px-2 text-[11px]">{queries[i]?.data?.total??0}</span></h2><div className="space-y-3">{queries[i]?.isLoading?<p className="text-sm text-muted">{en?'Loading…':'లోడ్ అవుతోంది…'}</p>:queries[i]?.data?.articles.length?queries[i]?.data?.articles.map(a=>{const overdue=Date.now()-new Date(a.updated_at).getTime()>30*60000;return <article key={a.id} className="rounded-card border border-rule bg-white p-3 shadow-sm"><div className="mb-2 flex justify-between gap-2"><span className="font-mono text-[10px] text-muted">#{a.id} · {a.short_id}</span><span className={`rounded-chip px-2 py-0.5 text-[10px] font-bold ${overdue?'bg-breaking-tint text-breaking':'bg-rule-soft text-muted'}`}>{ageLabel(a,en)}</span></div><Link to={`/admin/articles/${a.id}/edit`} className="th block text-[16px] font-bold leading-telugu hover:text-brand">{en?(a.title_en||a.title_te):a.title_te}</Link><div className="mt-3 flex gap-2"><button disabled={transition.isPending} onClick={()=>transition.mutate({id:a.id,action:c.action})} className="rounded-control bg-brand px-3 py-2 text-[11px] font-bold text-white">{en?c.actionEn:c.actionTe}</button>{c.state!=='APPROVED'?<button disabled={transition.isPending} onClick={()=>transition.mutate({id:a.id,action:'request-changes'})} className="rounded-control border border-rule px-3 py-2 text-[11px] font-semibold">{en?'Request changes':'మార్పులు'}</button>:null}</div></article>}):<p className="rounded-control border border-dashed border-rule bg-white p-4 text-center text-[12px] text-muted">{en?'No articles in this queue.':'ఈ క్యూలో కథనాలు లేవు.'}</p>}</div></section>)}</div></main>}
